name: to_do_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0' # Ensure Dart SDK version supports `super-parameters`

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # Example dependency, adjust as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Example dev dependency, adjust as needed

flutter:
  uses-material-design: true
  assets:
    - assets/yellow_logo.png

